apiVersion: apps/v1
kind: Deployment
metadata:
  name: connections-deployment
  labels:
    app: connections
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connections
  template:
    metadata:
      labels:
        app: connections
    spec:
      serviceAccountName: connections-sa  # This comes from cluster/sa.yml
      containers:
        - name: connections
          image: vishnukrajan007/connections-app:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: mysecretname  # from sec.yml
                  key: connectionString

