apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connections-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: www.blueskyhive.com   # Change this to your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: connections-service
                port:
                  number: 80

